
targets:
  $default:
    builders:
      source_gen|combining_builder:
        enabled: true
      arch_gen|entity:
        enabled: true
      arch_gen|environment:
        enabled: true        
      arch_gen|use_this_concrete_on:
        enabled: true        

builders:
  entity:
    import: 'package:arch_gen/arch_gen/src/annotations/generators.dart'
    builder_factories: ["entityBuilder"]
    build_extensions: {".dart": ["entity.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  environment:
    import: 'package:arch_gen/arch_gen/src/annotations/generators.dart'
    builder_factories: ["environmentBuilder"]
    build_extensions: {".dart": ["environment.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]    
  use_this_concrete_on:
    import: 'package:arch_gen/arch_gen/src/annotations/generators.dart'
    builder_factories: ["useThisConcreteOnBuilder"]
    build_extensions: {".dart": [".use_this_concrete_on.json"]}
    auto_apply: dependents
    runs_before: ["arch_gen|environment"]
    build_to: cache
