targets:
  $default:
    builders:
      source_gen|combining_builder:
        enabled: true
      arch_gen|data_class:
        enabled: true

builders:
  data_class:
    import: 'package:arch_gen/arch_gen/src/annotations/generators.dart'
    builder_factories: ["dataClassBuilder"]
    build_extensions: {".dart": ["data_class.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]