name: arch_gen
description: Clean Architecture Generator
version: 0.0.1
homepage: https://github.com/dart-lang/source_gen

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  analyzer: ^5.5.0
  build: ^2.3.1
  meta: ^1.9.0
  source_gen: ^1.2.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
